name: Build and Deploy to Itch.io

on: push

jobs:
  buildForWindows:
    name: Build for StandaloneWindows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-StandaloneWindows
          restore-keys: Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows
          buildPath: build/StandaloneWindows

      - name: List Build Directory Contents
        run: ls -R build

      - uses: actions/upload-artifact@v3
        with:
          name: Build-StandaloneWindows
          path: build/StandaloneWindows

  itchio-deploy:
    name: Deploy to Itch.io
    needs: buildForWindows
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build-StandaloneWindows
          path: build/StandaloneWindows

      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip -d /usr/local/bin
          chmod +x /usr/local/bin/butler

      - name: Deploy to Itch.io
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        run: |
          butler push build/StandaloneWindows theoscreation/itchdeploygithubtest1:platform-windows